version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
      - export NODE_OPTIONS=--max_old_space_size=15000
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      - aws --version
      - npm install --prefix website/
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_linux_amd64.zip
      - unzip terraform.zip

  build:
    commands:
      - cd website/
      - node_modules/.bin/gatsby build --no-colors

  post_build:
    commands:
      - cd ../infrastructure
      - /usr/local/bin/aws dynamodb create-table \
        --table-name $DYNAMODB_NAME \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
      - /usr/local/bin/aws s3api create-bucket –bucket $BUCKET_NAME \
        –region $AWS_REGION \
        –create-bucket-configuration LocationConstraint=$AWS_REGION
      - "/usr/local/bin/aws s3api put-bucket-encryption –bucket $BUCKET_NAME \
        –server-side-encryption-configuration '{\'Rules\': [{\'ApplyServerSideEncryptionByDefault\':{\'SSEAlgorithm\': \'AES256\'}}]}"
      - /usr/local/bin/aws s3api put-bucket-versioning \
        --bucket $BUCKET_NAME \
        --versioning-configuration Status=Enabled
      - $PWD/terraform init -backend-config=bucket=$BUCKET_NAME \
        -backend-config=dynamodb_table=$DYNAMODB_NAME \
        -backend-config=key=$GITHUB_REPO \
        -backend-config=region=$AWS_REGION
      - $PWD/terraform plan -out=tfplan \
        -var-file=pro.tfvars \
        -var=aws_access_key=$AWS_ACCESS_KEY \
        -var=aws_secret_key=$AWS_SECRET_KEY \
        -var=github_token=$GITHUB_TOKEN \
        -var=alerting_sms_number=$ALERTING_SMS_NUMBER \
        -var=aws_region=$AWS_REGION
      - $PWD/terraform apply tfplan

cache:
  paths:
    - 'webiste/node_modules/**/*'
    - 'webiste/.cache/*'

artifacts:
  files:
    - '**/*'