version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.85.0/hugo_0.85.0_Linux-64bit.deb
      - dpkg -i hugo.deb
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_linux_amd64.zip
      - unzip -qq terraform.zip

  build:
    commands:
      - cd website/
      - git init
      - git submodule add https://github.com/hugo-toha/toha.git themes/toha
      - hugo

  post_build:
    commands:
      - cd ../infrastructure/
      - $PWD/terraform init -backend-config=bucket=$BUCKET_NAME -backend-config=dynamodb_table=$DYNAMODB_NAME -backend-config=key=$GITHUB_REPO -backend-config=region=$AWS_REGION
      - $PWD/terraform plan -out=tfplan -var-file=pro.tfvars -var=github_token=$GITHUB_TOKEN -var=alerting_sms_number=$ALERTING_SMS_NUMBER
      - $PWD/terraform apply tfplan

artifacts:
  files:
    - '**/*'
  base-directory: public