baseURL: https://info.destaben.dev
languageCode: en-us
title: "David Estabén"
theme: "toha"
languages:
  en:
    languageName: English
    weight: 1

server:
  headers:
  - for: /*
    values:
      Cache-Control: max-age 86400
      Cache-Control: s-maxage 86400

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON

enableEmoji: true

params:
  background: /images/site/background.jpg
  logo:
    main: /images/site/logo.png
    favicon: /images/site/logo.png

  gitRepo: https://github.com/destaben/personalwebsite
  gitBranch: source

  features:
    portfolio:
      enable: true
    blog:
      enable: false
    notes:
      enable: false
  enableTOC: true

  footer:
    enable: true
    template: footer.html
    navigation:
      enable: true
    contactMe:
      enable: true
    credentials:
      enable: true
    newsletter:
      enable: false
    disclaimer:
      enable: false